------------------------------------------------------------------------------------------
**************************************2016/02/20_16:55:18******************************************
python: can't open file 'uwkappa_Gau.py': [Errno 5] Input/output error
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[53911,1],9]
  Exit code:    2
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyError: "unable to open object (Symbol table: Can't open object)"
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
        oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
KeyError: "unable to open object (Symbol table: Can't open object)"
KeyErrorKeyError: "unable to open object (Symbol table: Can't open object)"
: "unable to open object (Symbol table: Can't open object)"
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
KeyError: "unable to open object (Symbol table: Can't open object)"
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
KeyError: "unable to open object (Symbol table: Can't open object)"
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
KeyError: "unable to open object (Symbol table: Can't open object)"
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
KeyError: "unable to open object (Symbol table: Can't open object)"
Traceback (most recent call last):
  File "get_bin2d.py", line 33, in <module>
    Pk_dd=f['data'][mpi_index[rank].tolist()]
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
KeyError: "unable to open object (Symbol table: Can't open object)"
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[53928,1],16]
  Exit code:    1
--------------------------------------------------------------------------
cp: 无法获取"/project/mtx/data/tide/data_halo/data/hm2/result_b" 的文件状态(stat): 没有那个文件或目录
cp: 无法获取"/project/mtx/data/tide/data_halo/data/hm2/result_W" 的文件状态(stat): 没有那个文件或目录
================================================================================
Cal wkkappa
Loading data  in  filename
Loading hdf5
Traceback (most recent call last):
  File "wkkappa.py", line 50, in <module>
    kappax=Tide.LoadDataOfhdf5(dir+'kappa3dx1.25.hdf5')
  File "/home/mtx/github/Tide/src/TIDES.py", line 41, in LoadDataOfhdf5
    data=f['data'].value
  File "/opt/python-2.7.5-mkl/lib/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 173, in h5py.h5o.open (h5py/h5o.c:3427)
KeyError: "unable to open object (Symbol table: Can't open object)"
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
**************************END IN:    2016/02/20_16:58:51******************************************

real	3m32.967s
user	0m4.583s
sys	0m3.501s
------------------------------------------------------------------------------------------
**************************************2016/02/20_16:58:51******************************************
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
Killed by signal 2.
rm: 无法删除"result_b": 没有那个文件或目录
rm: 无法删除"result_W": 没有那个文件或目录
**************************END IN:    2016/02/20_16:58:52******************************************

real	0m1.849s
user	0m0.246s
sys	0m0.281s
